name: Build Ubuntu Packages
env:
  app-name: 'smplayer'

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: 'xenial', os: 'ubuntu-16.04', qt: 4 }
          - { name: 'bionic', os: 'ubuntu-18.04', qt: 5 }
          - { name: 'focal', os: 'ubuntu-20.04', qt: 5 }

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Install sources
        uses: actions/checkout@v2
        with:
          path: ${{ env.app-name }}
          fetch-depth: 0

      - name: Install development packages
        run: |
            sudo apt-get update
            sudo apt-get install zlib1g-dev fakeroot build-essential devscripts debhelper g++

      - name: Install Qt 4
        run: sudo apt-get install libqt4-dev libqtwebkit-dev
        if: ${{ matrix.config.qt == 4 }}

      - name: Install Qt 5
        run: sudo apt-get install qtbase5-dev qt5-qmake qt5-default qtscript5-dev qttools5-dev-tools qtbase5-private-dev libqt5webkit5-dev
        if: ${{ matrix.config.qt == 5 }}

      - name: Prepare sources
        run: |
            cd ${{ env.app-name }}
            ln -s debian-orig debian
            cp debian-orig/changelog-orig debian-orig/changelog
            ./get_version.sh
            VERSION=`cat version`~${{ matrix.config.name }}
            dch -v $VERSION "Development version"
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compile ${{ env.app-name }}
        run: cd ${{ env.app-name }} && fakeroot debian/rules build

      - name: Build package
        run: cd ${{ env.app-name }} && fakeroot debian/rules binary

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.app-name }}-${{ env.VERSION }}.deb
          path: ./*.deb

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
