name: Build SMPlayer with Qt 5

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install development packages
        run: |
            sudo apt-get update
            sudo apt-get install zlib1g-dev fakeroot build-essential devscripts debhelper g++
            sudo apt-get install qtbase5-dev qt5-qmake qt5-default qtscript5-dev qttools5-dev-tools qtbase5-private-dev

      - name: Build smplayer
        run: ./create_deb.sh
