name: Build Windows with smtubelib

on:
  workflow_dispatch:
  #release:
  #  types: [published]

jobs:
  build:
    runs-on: windows-latest
      
    steps:
      - name: Checkout
        #run: svn co https://github.com/smplayer-dev/smplayer-build.git/trunk .
        run: git clone https://github.com/smplayer-dev/smplayer-build.git .

      - name: Install sources (normal)
        uses: actions/checkout@v2
        with:
          path: packages/smplayer
          fetch-depth: 0

      - name: Install smtube
        #run: svn co https://github.com/smplayer-dev/smtube.git/trunk packages/smtube
        run: git clone --depth 1 https://github.com/smplayer-dev/smtube.git packages/smtube

      - name: Install themes
        run: |
            #svn co https://github.com/smplayer-dev/smplayer-themes.git/trunk packages\smplayer-themes
            #svn co https://github.com/smplayer-dev/smplayer-skins.git/trunk packages\smplayer-skins
            git clone --depth 1 https://github.com/smplayer-dev/smplayer-themes.git packages\smplayer-themes
            git clone --depth 1 https://github.com/smplayer-dev/smplayer-skins.git packages\smplayer-skins

      - name: Install mplayer and mpv
        run: .\uncompress_players.cmd

      - name: Install Qt (64 bit)
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'
          tools: 'tools_mingw,8.1.0-1,qt.tools.win64_mingw810 tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'

      - name: Set mingw32 path (64 bit)
        run: echo "$env:IQTA_TOOLS\mingw810_64\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Download QtWebkit (64 bit)
        run: Invoke-WebRequest -Uri https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-Windows-Windows_10-Mingw73-Windows-Windows_10-X86_64.7z -OutFile qtwebkit.7z

      - name: Extract QtWebKit
        shell: bash
        run: 7z x qtwebkit.7z -o$Qt5_Dir

      - name: Compile themes
        run: .\compile_themes.cmd

      - name: Compile smplayer
        run: .\compile_smplayer_with_smtube.cmd

      - name: Install
        run: .\install.cmd

      - name: Create installer
        run: |
           .\nsis.cmd
           $filename = Get-Content packages\BUILD\installer_filename.txt -TotalCount 1
           echo "PACKAGEFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Rename package
        shell: bash
        run: |
            PACKAGEFILENAME=${{ env.PACKAGEFILENAME }}
            extension="${PACKAGEFILENAME##*.}"
            filename="${PACKAGEFILENAME%.*}"
            new_filename="$filename-smt.$extension"
            cd packages/BUILD/output/
            mv $PACKAGEFILENAME $new_filename
            echo "PACKAGEFILENAME=$new_filename" >> $GITHUB_ENV

      - name: Create artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEFILENAME }}
          path: packages\BUILD\output\${{ env.PACKAGEFILENAME }}
