name: Build SMPlayer on Mac OS
env:
  #mplayer-url: https://github.com/smplayer-dev/mplayer-mod/releases/download/v1.4-84/mplayer-macos-10.14-av.tar.bz2
  mplayer-url: https://github.com/smplayer-dev/mplayer-mod/releases/download/v1.5-110/mplayer-macos-10.15-av.tar.bz2
  #mpv-url: https://github.com/smplayer-dev/mpv/releases/download/v0.34.0-mod/mpv-macos-10.14-av.tar.bz2
  #mpv-url: https://github.com/smplayer-dev/mpv/releases/download/v0.35.1-mod/mpv-macos-11.tar.bz2
  #mpv-url: https://github.com/smplayer-dev/mpv/releases/download/v0.35.1-mod/mpv-macos-10.15-av.tar.bz2
  #mpv-url: https://github.com/smplayer-dev/mpv/releases/download/v0.35.1-mod-2/mpv-macos-10.15-av.tar.bz2
  mpv-url: https://github.com/smplayer-dev/mpv/releases/download/v0.36.0/mpv-macos-10.15-av.tar.bz2

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    #runs-on: macos-10.15
    #runs-on: macos-11
    #runs-on: macos-12
    #runs-on: macos-13
    runs-on: macos-15-intel

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: packages/smplayer

      - name: Get version
        run: |
            cd packages/smplayer
            ./get_version.sh
            VERSION=`cat version`-macos
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install build dependencies
        run: brew install create-dmg

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          #version: '5.12.11'
          version: '5.15.2'
          host: 'mac'

      - name: Install QtWebkit
        if: ${{false}}
        run: |
            wget https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z -O qtwebkit.7z
            7z x qtwebkit.7z -o$Qt5_Dir

      - name: Install smtube sources
        if: ${{false}}
        run: git clone https://github.com/smplayer-dev/smtube.git packages/smtube

      - name: Set xcode
        if: ${{false}}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10.3'

      - name: Compile
        run: |
            cd packages/smplayer
            ./compile_mac.sh

      - name: Install themes
        run: |
            git clone https://github.com/smplayer-dev/smplayer-themes.git packages/smplayer-themes
            cd packages/smplayer-themes
            make
            make install THEMES_PATH=../smplayer/package/SMPlayer.app/Contents/Resources/themes

      - name: Install skins
        run: |
            git clone https://github.com/smplayer-dev/smplayer-skins.git packages/smplayer-skins
            cd packages/smplayer-skins
            make
            make install THEMES_PATH=../smplayer/package/SMPlayer.app/Contents/Resources/themes

      - name: Install mplayer
        run: |
            wget ${{ env.mplayer-url }} -O mplayer-macos.tar.bz2
            tar -xvf mplayer-macos.tar.bz2 -C packages/smplayer/package/SMPlayer.app --strip-components=1

      - name: Install mpv
        run: |
            wget ${{ env.mpv-url }} -O  mpv-macos.tar.bz2 
            tar -xvf mpv-macos.tar.bz2 -C /tmp/
            cp /tmp/mpv.app/Contents/MacOS/mpv packages/smplayer/package/SMPlayer.app/Contents/MacOS/
            cp /tmp/mpv.app/Contents/MacOS/lib/* packages/smplayer/package/SMPlayer.app/Contents/MacOS/lib/

      - name: Create dmg
        run: |
            cd packages/smplayer
            ./create_dmg,sh
            ls -l package/

      - name: Create artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: smplayer-${{env.VERSION}}
          path: packages/smplayer/package/*.dmg

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./packages/smplayer/package/*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
